theme: jekyll-theme-cayman

#Site settings
title: 文档知识库
email: info@kucodeai.com
description: 酷编程人工智能教育
baseurl: "/docs/"
url: "https://docs.kucodeai.com"
github_username: kucodeai

#timezone : Asis/Shanghai
timezone: Asia/Shanghai

#encoding : utf-8
encoding: utf-8

#setting permalink value
permalink: /:year/:month/:day/:title.html

paginate: 5
paginate_path: "docs/page:num/"

kramdown:
    parse_block_html: true

#Build settings
